In [ ]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
dataset=pd.read_excel('Online Retail.xlsx')

In [ ]:
dataset.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [ ]:
dataset.shape

(541909, 8)

In [ ]:
dataset.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [ ]:
dataset.dropna(axis=0,subset=['InvoiceNo'],inplace=True)

In [ ]:
dataset['Description']=dataset['Description'].str.strip()
dataset.dropna(axis=0,subset=['InvoiceNo'],inplace=True)
dataset['InvoiceNo']=dataset['InvoiceNo'].astype('str')
dataset=dataset[dataset['InvoiceNo'].str.contains('C')]
dataset.head()

  InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [ ]:
dataset['Country'].value_counts()

Country
United Kingdom          487622
Germany                   9042
France                    8408
EIRE                      7894
Spain                     2485
Netherlands               2363
Belgium                   2031
Switzerland               1967
Portugal                  1501
Australia                 1185
Norway                    1072
Italy                      758
Channel Islands            748
Finland                    685
Cyprus                     614
Sweden                     451
Unspecified                446
Austria                    398
Denmark                    380
Poland                     330
Japan                      321
Israel                     295
Hong Kong                  284
Singapore                  222
Iceland                    182
USA                        179
Canada                     151
Greece                     145
Malta                      112
United Arab Emirates        68
European Community          60
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              25
Bahrain                     18
Saudi Arabia                 9
Name: count, dtype: int64

In [ ]:
mybasket=(dataset[dataset['Country']=='Germany'].groupby(['InvoiceNo','Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0).set_index('InvoiceNo'))

In [ ]:
mybasket

Description  10 COLOUR SPACEBOY PEN  ...  ZINC WILLIE WINKIE  CANDLE STICK
InvoiceNo                            ...
536527                          0.0  ...                               0.0
536840                          0.0  ...                               0.0
536861                          0.0  ...                               0.0
536967                          0.0  ...                               0.0
536983                          0.0  ...                               0.0
...                             ...  ...                               ...
581266                          0.0  ...                               0.0
581494                          0.0  ...                               0.0
581570                          0.0  ...                               0.0
581574                          0.0  ...                               0.0
581578                          0.0  ...                               0.0

[457 rows x 1695 columns]

In [ ]:
def my_bas(x):
  if x<=0:
    return 0
  if x>=1:
    return 1
b_c=mybasket.applymap(my_bas)
mybasket=b_c

/tmp/ipykernel_4375/581441020.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  b_c=mybasket.applymap(my_bas)

In [ ]:
mybasket.head()

Description  10 COLOUR SPACEBOY PEN  ...  ZINC WILLIE WINKIE  CANDLE STICK
InvoiceNo                            ...
536527                            0  ...                                 0
536840                            0  ...                                 0
536861                            0  ...                                 0
536967                            0  ...                                 0
536983                            0  ...                                 0

[5 rows x 1695 columns]

In [ ]:
f_i=apriori(mybasket,min_support=0.07,use_colnames=True)
f_i

     support                                           itemsets
0   0.102845                           (6 RIBBONS RUSTIC CHARM)
1   0.070022                        (ALARM CLOCK BAKELIKE PINK)
2   0.072210                                (GUMBALL COAT RACK)
3   0.091904                           (JAM MAKING SET PRINTED)
4   0.078775                          (JUMBO BAG RED RETROSPOT)
5   0.100656                       (JUMBO BAG WOODLAND ANIMALS)
6   0.078775                               (LUNCH BAG WOODLAND)
7   0.085339                  (PACK OF 72 RETROSPOT CAKE CASES)
8   0.115974                    (PLASTERS IN TIN CIRCUS PARADE)
9   0.107221                         (PLASTERS IN TIN SPACEBOY)
10  0.070022                        (PLASTERS IN TIN STRONGMAN)
11  0.137856                 (PLASTERS IN TIN WOODLAND ANIMALS)
12  0.818381                                          (POSTAGE)
13  0.070022                      (RED RETROSPOT CHARLOTTE BAG)
14  0.070022                                (RED RETROSPOT CUP)
15  0.096280                    (RED TOADSTOOL LED NIGHT LIGHT)
16  0.137856                         (REGENCY CAKESTAND 3 TIER)
17  0.157549                (ROUND SNACK BOXES SET OF 4 FRUITS)
18  0.245077               (ROUND SNACK BOXES SET OF4 WOODLAND)
19  0.070022                       (SET OF 3 REGENCY CAKE TINS)
20  0.102845                               (SPACEBOY LUNCH BOX)
21  0.078775                (STRAWBERRY LUNCH BOX WITH CUTLERY)
22  0.126915                           (WOODLAND CHARLOTTE BAG)
23  0.091904                  (POSTAGE, 6 RIBBONS RUSTIC CHARM)
24  0.074398                  (JAM MAKING SET PRINTED, POSTAGE)
25  0.087527              (JUMBO BAG WOODLAND ANIMALS, POSTAGE)
26  0.100656           (PLASTERS IN TIN CIRCUS PARADE, POSTAGE)
27  0.100656                (PLASTERS IN TIN SPACEBOY, POSTAGE)
28  0.118162        (PLASTERS IN TIN WOODLAND ANIMALS, POSTAGE)
29  0.074398  (ROUND SNACK BOXES SET OF4 WOODLAND, PLASTERS ...
30  0.080963           (RED TOADSTOOL LED NIGHT LIGHT, POSTAGE)
31  0.120350                (REGENCY CAKESTAND 3 TIER, POSTAGE)
32  0.150985       (ROUND SNACK BOXES SET OF 4 FRUITS, POSTAGE)
33  0.225383      (ROUND SNACK BOXES SET OF4 WOODLAND, POSTAGE)
34  0.091904                      (SPACEBOY LUNCH BOX, POSTAGE)
35  0.115974                  (WOODLAND CHARLOTTE BAG, POSTAGE)
36  0.131291  (ROUND SNACK BOXES SET OF4 WOODLAND, ROUND SNA...
37  0.070022  (ROUND SNACK BOXES SET OF4 WOODLAND, SPACEBOY ...
38  0.124726  (ROUND SNACK BOXES SET OF4 WOODLAND, ROUND SNA...

In [ ]:
rules=association_rules(f_i,metric='lift',min_threshold=1)
rules

                                          antecedents  ... kulczynski
0                                           (POSTAGE)  ...   0.502958
1                            (6 RIBBONS RUSTIC CHARM)  ...   0.502958
2                        (JUMBO BAG WOODLAND ANIMALS)  ...   0.488259
3                                           (POSTAGE)  ...   0.488259
4                     (PLASTERS IN TIN CIRCUS PARADE)  ...   0.495460
5                                           (POSTAGE)  ...   0.495460
6                          (PLASTERS IN TIN SPACEBOY)  ...   0.530885
7                                           (POSTAGE)  ...   0.530885
8                  (PLASTERS IN TIN WOODLAND ANIMALS)  ...   0.500764
9                                           (POSTAGE)  ...   0.500764
10               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.421627
11                 (PLASTERS IN TIN WOODLAND ANIMALS)  ...   0.421627
12                    (RED TOADSTOOL LED NIGHT LIGHT)  ...   0.469920
13                                          (POSTAGE)  ...   0.469920
14                         (REGENCY CAKESTAND 3 TIER)  ...   0.510037
15                                          (POSTAGE)  ...   0.510037
16                (ROUND SNACK BOXES SET OF 4 FRUITS)  ...   0.571413
17                                          (POSTAGE)  ...   0.571413
18               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.597522
19                                          (POSTAGE)  ...   0.597522
20                               (SPACEBOY LUNCH BOX)  ...   0.502958
21                                          (POSTAGE)  ...   0.502958
22                           (WOODLAND CHARLOTTE BAG)  ...   0.527752
23                                          (POSTAGE)  ...   0.527752
24               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.684524
25                (ROUND SNACK BOXES SET OF 4 FRUITS)  ...   0.684524
26               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.483283
27                               (SPACEBOY LUNCH BOX)  ...   0.483283
28  (ROUND SNACK BOXES SET OF4 WOODLAND, ROUND SNA...  ...   0.551203
29      (ROUND SNACK BOXES SET OF4 WOODLAND, POSTAGE)  ...   0.672532
30       (ROUND SNACK BOXES SET OF 4 FRUITS, POSTAGE)  ...   0.667508
31               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.667508
32                (ROUND SNACK BOXES SET OF 4 FRUITS)  ...   0.672532
33                                          (POSTAGE)  ...   0.551203

[34 rows x 14 columns]

In [ ]:
mybasket['SPACEBOY LUNCH BOX'].sum()

np.int64(47)

In [ ]:
rules[(rules['lift']>=5 & (rules['confidence']>=0.3))]

                                          antecedents  ... kulczynski
0                                           (POSTAGE)  ...   0.502958
1                            (6 RIBBONS RUSTIC CHARM)  ...   0.502958
2                        (JUMBO BAG WOODLAND ANIMALS)  ...   0.488259
3                                           (POSTAGE)  ...   0.488259
4                     (PLASTERS IN TIN CIRCUS PARADE)  ...   0.495460
5                                           (POSTAGE)  ...   0.495460
6                          (PLASTERS IN TIN SPACEBOY)  ...   0.530885
7                                           (POSTAGE)  ...   0.530885
8                  (PLASTERS IN TIN WOODLAND ANIMALS)  ...   0.500764
9                                           (POSTAGE)  ...   0.500764
10               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.421627
11                 (PLASTERS IN TIN WOODLAND ANIMALS)  ...   0.421627
12                    (RED TOADSTOOL LED NIGHT LIGHT)  ...   0.469920
13                                          (POSTAGE)  ...   0.469920
14                         (REGENCY CAKESTAND 3 TIER)  ...   0.510037
15                                          (POSTAGE)  ...   0.510037
16                (ROUND SNACK BOXES SET OF 4 FRUITS)  ...   0.571413
17                                          (POSTAGE)  ...   0.571413
18               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.597522
19                                          (POSTAGE)  ...   0.597522
20                               (SPACEBOY LUNCH BOX)  ...   0.502958
21                                          (POSTAGE)  ...   0.502958
22                           (WOODLAND CHARLOTTE BAG)  ...   0.527752
23                                          (POSTAGE)  ...   0.527752
24               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.684524
25                (ROUND SNACK BOXES SET OF 4 FRUITS)  ...   0.684524
26               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.483283
27                               (SPACEBOY LUNCH BOX)  ...   0.483283
28  (ROUND SNACK BOXES SET OF4 WOODLAND, ROUND SNA...  ...   0.551203
29      (ROUND SNACK BOXES SET OF4 WOODLAND, POSTAGE)  ...   0.672532
30       (ROUND SNACK BOXES SET OF 4 FRUITS, POSTAGE)  ...   0.667508
31               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   0.667508
32                (ROUND SNACK BOXES SET OF 4 FRUITS)  ...   0.672532
33                                          (POSTAGE)  ...   0.551203

[34 rows x 14 columns]