In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset=pd.read_csv('titanic.csv')

In [ ]:
dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
dataset.head()   # Prothom theke 5 ta data show korbe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
dataset.head(10)   # Prothom theke 10 ta data show korbe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
dataset.tail(10)   # Sesh theke 10 ta data show korbe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# feature gular naam janar jonne
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
# sob numerical column er jonnr min, max, count etc...shob ashbe (numerical result gular jonne dekhabe)
dataset.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# dataset er vitore kono null value ase kina check dibe
# true mane faka ase
dataset.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
# age=177 mane 177 ta faka value ase
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# abar dataset read korbo karon amake oi 3 ta column niye kaj korte hobe
# etake ekhn df naam dibo
df= pd.read_csv('titanic.csv',usecols=["Age","Cabin","Embarked"])

In [ ]:
df

      Age Cabin Embarked
0    22.0   NaN        S
1    38.0   C85        C
2    26.0   NaN        S
3    35.0  C123        S
4    35.0   NaN        S
..    ...   ...      ...
886  27.0   NaN        S
887  19.0   B42        S
888   NaN   NaN        S
889  26.0  C148        C
890  32.0   NaN        Q

[891 rows x 3 columns]

**Mean diye replace**

Age e joto null value ase seitake mean, median, mode 3 ta diye replace korbo. erpr main dataset er sathe compare korbo graphicsl plot diye . dekhbo je kar poriborton sobcheye kom. jeitar porborton sobcheye kom seita diye e main dataset ke replace korbo

In [ ]:
# Mean diye replace
mean= df["Age"].mean()

In [ ]:
# Creating a Function
# diu= parameter ...eikhetre jehetu ei function ta dataset ke chine na sehetu dataset er variable diu
# Age ke pass korar jonne variable namr parameter use kortesi
# ei function er kaj Age_mean toiri kore oikhan er null value ke mean diye replace kora

def input_nan(diu,variable,mean):
  diu[variable+"mean"]=diu[variable].fillna(mean)

In [ ]:
# function call
input_nan(df,"Age",mean)

In [ ]:
df

      Age Cabin Embarked    Agemean
0    22.0   NaN        S  22.000000
1    38.0   C85        C  38.000000
2    26.0   NaN        S  26.000000
3    35.0  C123        S  35.000000
4    35.0   NaN        S  35.000000
..    ...   ...      ...        ...
886  27.0   NaN        S  27.000000
887  19.0   B42        S  19.000000
888   NaN   NaN        S  29.699118
889  26.0  C148        C  26.000000
890  32.0   NaN        Q  32.000000

[891 rows x 4 columns]

In [ ]:
df.isnull().sum()

Age         177
Cabin       687
Embarked      2
Agemean       0
dtype: int64

**Mode diye replace**

In [ ]:
# Mode diye replace so mode er man ber korbo
# [0] disi karon eita na dile index soho ashbe. mode diye replace hobe  na
mode= df["Age"].mode()[0]
mode

np.float64(24.0)

In [ ]:
def input_nan(diu,variable,mode):
  diu[variable+"mode"]=diu[variable].fillna(mode)

In [ ]:
# function call
input_nan(df,"Age",mode)

In [ ]:
df

      Age Cabin Embarked    Agemean  Agemode
0    22.0   NaN        S  22.000000     22.0
1    38.0   C85        C  38.000000     38.0
2    26.0   NaN        S  26.000000     26.0
3    35.0  C123        S  35.000000     35.0
4    35.0   NaN        S  35.000000     35.0
..    ...   ...      ...        ...      ...
886  27.0   NaN        S  27.000000     27.0
887  19.0   B42        S  19.000000     19.0
888   NaN   NaN        S  29.699118     24.0
889  26.0  C148        C  26.000000     26.0
890  32.0   NaN        Q  32.000000     32.0

[891 rows x 5 columns]

In [ ]:
df.isnull().sum()

Age         177
Cabin       687
Embarked      2
Agemean       0
Agemode       0
dtype: int64

**Median diye replace**

In [ ]:
median= df["Age"].median()
median

28.0

In [ ]:
def input_nan(diu,variable,moedian):
  diu[variable+"median"]=diu[variable].fillna(median)

In [ ]:
# function call
input_nan(df,"Age",median)

In [ ]:
df

      Age Cabin Embarked    Agemean  Agemode  Agemedian
0    22.0   NaN        S  22.000000     22.0       22.0
1    38.0   C85        C  38.000000     38.0       38.0
2    26.0   NaN        S  26.000000     26.0       26.0
3    35.0  C123        S  35.000000     35.0       35.0
4    35.0   NaN        S  35.000000     35.0       35.0
..    ...   ...      ...        ...      ...        ...
886  27.0   NaN        S  27.000000     27.0       27.0
887  19.0   B42        S  19.000000     19.0       19.0
888   NaN   NaN        S  29.699118     24.0       28.0
889  26.0  C148        C  26.000000     26.0       26.0
890  32.0   NaN        Q  32.000000     32.0       32.0

[891 rows x 6 columns]

In [ ]:
df.isnull().sum()

Age          177
Cabin        687
Embarked       2
Agemean        0
Agemode        0
Agemedian      0
dtype: int64